In [0]:
import numpy as np
import random

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
arr = np.random.randint(51, size=10)
print(arr)
print(f"a média do array é {arr.mean()}")
print(f"O desvio padrão é {arr.std()}")

[50 47 49 10 40 30 20 48 23 32]
a média do array é 34.9
O desvio padrão é 13.367497896016292


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)
print(arr)
arr_sqrt = np.sqrt(arr[arr <= 0.5])
print(f" Lista com as raizes {arr_sqrt}")

[0.81802233 0.43779316 0.70004793 0.0796733  0.47263762 0.69949109
 0.64029619 0.54194693 0.63954747 0.90189293]
 Lista com as raizes [0.6616594  0.2822646  0.68748645]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
np.amax([[-50], [10]], axis=-1, initial=0)

In [0]:
matriz = np.random.rand(3,3,3)
print(matriz)
print("só linhas")
print(np.amax(matriz, axis=1))

[[[0.95764832 0.95843732 0.19228705]
  [0.36186716 0.59261544 0.55105805]
  [0.46075323 0.33885257 0.7972839 ]]

 [[0.1603     0.59343662 0.43313289]
  [0.89450512 0.4355841  0.25147441]
  [0.9717708  0.27150317 0.78112242]]

 [[0.11119576 0.33297319 0.73523782]
  [0.97714903 0.61435207 0.46362129]
  [0.99887765 0.70264832 0.01710032]]]
só linhas
[[0.95764832 0.95843732 0.7972839 ]
 [0.9717708  0.59343662 0.78112242]
 [0.99887765 0.70264832 0.73523782]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
# Criar uma matriz de tamanho 5x5 com valores aleatórios
matriz = np.random.rand(5, 5)

# Subtrair a média de cada linha da matriz
# axis=1 --> a linha
# axis=0 --> a coluna
media = np.mean(matriz, axis=1)
matriz_linha_media = matriz - media[:, np.newaxis]

print("Matriz original:\n", matriz)
print("Média de cada linha:\n", media)
print("Matriz com a média de cada linha subtraída:\n", matriz_linha_media)

Matriz original:
 [[0.24106963 0.07877268 0.30211054 0.52969281 0.27261216]
 [0.41172286 0.84472844 0.46640454 0.82156462 0.47776608]
 [0.58093681 0.32885958 0.52683082 0.42469395 0.25379804]
 [0.00605881 0.40543377 0.61017472 0.49694764 0.7628698 ]
 [0.94340711 0.6796275  0.65645273 0.16091296 0.40457582]]
Média de cada linha:
 [0.28485156 0.60443731 0.42302384 0.45629695 0.56899522]
Matriz com a média de cada linha subtraída:
 [[-0.04378193 -0.20607888  0.01725897  0.24484125 -0.01223941]
 [-0.19271445  0.24029113 -0.13803277  0.21712731 -0.12667123]
 [ 0.15791297 -0.09416426  0.10380698  0.00167011 -0.1692258 ]
 [-0.45023814 -0.05086318  0.15387777  0.04065069  0.30657285]
 [ 0.37441189  0.11063228  0.08745751 -0.40808227 -0.16441941]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
# Criar uma matriz de tamanho 4x4 com valores aleatórios
matriz = np.random.rand(4, 4)

# Calcular a média e o desvio padrão das diagonais da matriz
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

# Exibir os resultados
print("Matriz:\n", matriz)
print("Diagonal principal:\n", diag_principal)
print("Diagonal secundária:\n", diag_secundaria)
print("Média das diagonais:", media_diag)
print("Desvio padrão das diagonais:", std_diag)

Matriz:
 [[0.23706281 0.47309238 0.53481745 0.33806592]
 [0.19246998 0.94853662 0.56731666 0.9260265 ]
 [0.54286478 0.03686341 0.03870268 0.89482046]
 [0.39851863 0.34940283 0.65395083 0.24146709]]
Diagonal principal:
 [0.23706281 0.94853662 0.03870268 0.24146709]
Diagonal secundária:
 [0.33806592 0.56731666 0.03686341 0.39851863]
Média das diagonais: 0.3508167264511467
Desvio padrão das diagonais: 0.2800576965550531
